const ErrorCode = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_INVALID: 'TOKEN_INVALID',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  DUPLICATE_DATA: 'DUPLICATE_DATA',
  BUSINESS_RULE: 'BUSINESS_RULE',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
};

module.exports = ErrorCode;
